image:
  - Visual Studio 2019
  - macos-monterey
  - Ubuntu

init:
  # Uncomment the line below to enable RDP access on AppVeyor
  # - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

branches:
  only:
    - main
    - /^rel\-*/

pull_requests:
  do_not_increment_build_number: true

artifacts:
  - path: dist/*.whl

environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true

matrix:
  fast_finish: true

build_script:

# Linux and macOS builds.
- sh: >-

    # =======================================================================
    #   Set up environment variables
    # =======================================================================

    DT_HARNESS="AppVeyor"

    MAIN_BUILD_ID=`git rev-list --count main`


    # Do not take into account the AppVeyor's additional merge commit

    BRANCH_BUILD_ID=`expr $MAIN_BUILD_ID - 1`


    if [ ! -z $APPVEYOR_PULL_REQUEST_NUMBER ]; then

      if [ APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH == "rel\-"* ]; then
        export DT_RELEASE="True"
      else
        export DT_BUILD_SUFFIX="PR$APPVEYOR_PULL_REQUEST_NUMBER.$BRANCH_BUILD_ID"
      fi

    elif [ APPVEYOR_REPO_BRANCH == "main" ]; then
      export DT_BUILD_NUMBER=$MAIN_BUILD_ID
    elif [ APPVEYOR_REPO_BRANCH == "rel\-"* ]; then
      export DT_RELEASE="True"
    else
      export DT_BUILD_SUFFIX="$APPVEYOR_REPO_BRANCH.$BRANCH_BUILD_ID"
    fi


    # =======================================================================
    #   Print debug information
    # =======================================================================

    echo "APPVEYOR_REPO_BRANCH = $APPVEYOR_REPO_BRANCH"

    echo "APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH = $APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH"

    echo "APPVEYOR_PULL_REQUEST_NUMBER = $APPVEYOR_PULL_REQUEST_NUMBER"

    echo "MAIN_BUILD_ID = $MAIN_BUILD_ID"

    echo "BRANCH_BUILD_ID = $BRANCH_BUILD_ID"

    echo "DT_RELEASE = $DT_RELEASE"

    echo "DT_BUILD_NUMBER = $DT_BUILD_NUMBER"

    echo "DT_BUILD_SUFFIX = $DT_BUILD_SUFFIX"


    # =======================================================================
    #   Build and test wheel for Python 3.11
    # =======================================================================

    source $HOME/venv3.11/bin/activate

    python -V

    python ci/ext.py wheel

    DT_WHEEL=`ls dist/*-cp311-*.whl`

    echo "----- _build_info.py for Python 3.11 ------------------------------"

    cat src/datatable/_build_info.py

    echo "------------------------------------------------------------------"

    python -m pip install --upgrade pip

    python -m pip install $DT_WHEEL

    python -m pip install pytest docutils pandas pyarrow

    python -m pytest -ra --maxfail=10 -Werror -vv --showlocals ./tests/



# Windows builds.
#
# We use PowerShell that has more powerful syntax
# than the standard command prompt. Unfortunately, PowerShell only takes
# into account exit code of the last command and, if other commands fail,
# the build can still be marked as green. Partially this problem is solved
# by setting `$ErrorActionPreference` to `"Stop"`, that works well with
# cmdlets. However, ultimately every PowerShell command should be followed
# by the check `if(!$?) { Exit $LASTEXITCODE }`, that will stop the build
# on the first failed command. Since we don't want to make the code too
# cumbersome, here we only check the exit status of `pytest` that is still
# a pretty good indicator.

- ps: >-

    # =======================================================================
    #   Set up environment variables
    # =======================================================================

    $ErrorActionPreference = "Stop"

    $env:DT_HARNESS = "AppVeyor"

    $DEFAULT_PATH = $env:PATH

    $MAIN_BUILD_ID = git rev-list --count main


    # Do not take into account the AppVeyor's additional merge commit

    $BRANCH_BUILD_ID = (git rev-list --count main) - 1

    if ($env:APPVEYOR_PULL_REQUEST_NUMBER -ne $null) {
      if ($env:APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH -match "^rel\-") {
        $env:DT_RELEASE = "True"
      } else {
        $env:DT_BUILD_SUFFIX = "PR$env:APPVEYOR_PULL_REQUEST_NUMBER.$BRANCH_BUILD_ID"
      }
    }
    elseif ($env:APPVEYOR_REPO_BRANCH -eq "main") {
      $env:DT_BUILD_NUMBER = $MAIN_BUILD_ID
    }
    elseif ($env:APPVEYOR_REPO_BRANCH -match "^rel\-") {
      $env:DT_RELEASE = "True"
    }
    else {
      $env:DT_BUILD_SUFFIX = "$env:APPVEYOR_REPO_BRANCH.$BRANCH_BUILD_ID"
    }


    # =======================================================================
    #   Print debug information
    # =======================================================================

    echo "DEFAULT_PATH = $DEFAULT_PATH"

    echo "APPVEYOR_REPO_BRANCH = $env:APPVEYOR_REPO_BRANCH"

    echo "APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH = $env:APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH"

    echo "APPVEYOR_PULL_REQUEST_NUMBER = $env:APPVEYOR_PULL_REQUEST_NUMBER"

    echo "MAIN_BUILD_ID = $MAIN_BUILD_ID"

    echo "BRANCH_BUILD_ID = $BRANCH_BUILD_ID"

    echo "DT_RELEASE = $env:DT_RELEASE"

    echo "DT_BUILD_NUMBER = $env:DT_BUILD_NUMBER"

    echo "DT_BUILD_SUFFIX = $env:DT_BUILD_SUFFIX"


    # =======================================================================
    #   Build and test wheel for Python 3.7
    # =======================================================================

    $env:PATH = "C:/Python37-x64;C:/Python37-x64/Scripts;$DEFAULT_PATH"

    python -V

    python ci/ext.py wheel

    $DT_WHEEL = ls dist/*-cp37-*.whl

    echo "DT_WHEEL = $DT_WHEEL"

    echo "----- _build_info.py for Python 3.7 ------------------------------"

    cat src/datatable/_build_info.py

    echo "------------------------------------------------------------------"

    python -m pip install --upgrade pip

    python -m pip install $DT_WHEEL

    python -m pip install pytest docutils pandas pyarrow

    python -m pytest -ra --maxfail=10 -Werror -vv --showlocals ./tests/

    if(!$?) { Exit $LASTEXITCODE }

    python -m pip uninstall -y $DT_WHEEL



    # =======================================================================
    #   Build and test wheel for Python 3.8
    # =======================================================================

    $env:PATH = "C:/Python38-x64;C:/Python38-x64/Scripts;$DEFAULT_PATH"

    python -V

    python ci/ext.py wheel

    $DT_WHEEL = ls dist/*-cp38-*.whl

    echo "DT_WHEEL = $DT_WHEEL"

    echo "----- _build_info.py for Python 3.8 ------------------------------"

    cat src/datatable/_build_info.py

    echo "------------------------------------------------------------------"

    python -m pip install --upgrade pip

    python -m pip install $DT_WHEEL

    python -m pip install pytest docutils pandas pyarrow

    python -m pytest -ra --maxfail=10 -Werror -vv --showlocals ./tests/

    if(!$?) { Exit $LASTEXITCODE }

    python -m pip uninstall -y $DT_WHEEL



    # =======================================================================
    #   Build and test wheel for Python 3.9
    # =======================================================================

    $env:PATH = "C:/Python39-x64;C:/Python39-x64/Scripts;$DEFAULT_PATH"

    python -V

    python ci/ext.py wheel

    $DT_WHEEL = ls dist/*-cp39-*.whl

    echo "DT_WHEEL = $DT_WHEEL"

    echo "----- _build_info.py for Python 3.9 ------------------------------"

    cat src/datatable/_build_info.py

    echo "------------------------------------------------------------------"

    python -m pip install --upgrade pip

    python -m pip install $DT_WHEEL

    python -m pip install pytest docutils pandas pyarrow

    python -m pytest -ra --maxfail=10 -Werror -vv --showlocals ./tests/

    if(!$?) { Exit $LASTEXITCODE }

    python -m pip uninstall -y $DT_WHEEL



    # =======================================================================
    #   Build and test debug wheel for Python 3.9
    # =======================================================================

    $env:PATH = "C:/Python39-x64;C:/Python39-x64/Scripts;$DEFAULT_PATH"

    python -V

    python ci/ext.py debugwheel

    $DT_WHEEL = ls dist/*debug-cp39-*.whl

    echo "DT_WHEEL = $DT_WHEEL"

    echo "----- _build_info.py for Python 3.9 debug wheel ------------------"

    cat src/datatable/_build_info.py

    echo "------------------------------------------------------------------"

    python -m pip install --upgrade pip

    python -m pip install $DT_WHEEL

    python -m pip install pytest docutils pandas pyarrow

    python -m pytest -ra --maxfail=10 -Werror -vv --showlocals ./tests/

    if(!$?) { Exit $LASTEXITCODE }

    python -m pip uninstall -y $DT_WHEEL



    # =======================================================================
    #   Build and test wheel for Python 3.10
    # =======================================================================

    $env:PATH = "C:/Python310-x64;C:/Python310-x64/Scripts;$DEFAULT_PATH"

    python -V

    python ci/ext.py wheel

    $DT_WHEEL = ls dist/*-cp310-*.whl

    echo "DT_WHEEL = $DT_WHEEL"

    echo "----- _build_info.py for Python 3.10 ------------------------------"

    cat src/datatable/_build_info.py

    echo "------------------------------------------------------------------"

    python -m pip install --upgrade pip

    python -m pip install $DT_WHEEL

    python -m pip install pytest docutils pandas pyarrow

    python -m pytest -ra --maxfail=10 -Werror -vv --showlocals ./tests/

    if(!$?) { Exit $LASTEXITCODE }

    python -m pip uninstall -y $DT_WHEEL


    # =======================================================================
    #   Build and test wheel for Python 3.11
    # =======================================================================

    $env:PATH = "C:/Python311-x64;C:/Python311-x64/Scripts;$DEFAULT_PATH"

    python -V

    python ci/ext.py wheel

    $DT_WHEEL = ls dist/*-cp311-*.whl

    echo "DT_WHEEL = $DT_WHEEL"

    echo "----- _build_info.py for Python 3.11 ------------------------------"

    cat src/datatable/_build_info.py

    echo "------------------------------------------------------------------"

    python -m pip install --upgrade pip

    python -m pip install $DT_WHEEL

    python -m pip install pytest docutils pandas pyarrow

    python -m pytest -ra --maxfail=10 -Werror -vv --showlocals ./tests/

    if(!$?) { Exit $LASTEXITCODE }

    python -m pip uninstall -y $DT_WHEEL

